server:
  port: 8083
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
seata:
  tx-service-group: gateway
  service:
    grouplist:
      default: 172.24.62.40:8091
    vgroup-mapping:
      gateway: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false