server:
  port: 8083
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
seata:
  tx-service-group: gateway
  service:
    grouplist:
      default: 172.24.62.40:8091
    vgroup-mapping:
      gateway: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false

#feign配置
feign:
  hystrix:
    enabled: true
    #sentinel:
    #enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false

#hystrix配置
hystrix:
  threadpool:
    default:
      coreSize: 300
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#ribbon配置
ribbon:
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 2
  #请求处理的超时时间
  ReadTimeout: 5000
  #请求连接的超时时间
  ConnectTimeout: 5000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
